# RNN Forward Propagation

This notebook explains the forward propagation process in Recurrent Neural Networks (RNNs).

## Introduction to RNNs

Recurrent Neural Networks (RNNs) are designed to handle sequential data by maintaining a hidden state that captures information from previous time steps. Unlike feedforward networks, RNNs have connections that form cycles, allowing them to process sequences of arbitrary length.

## Forward Propagation in RNNs

Forward propagation in RNNs involves computing the hidden states and outputs for each time step in the sequence. The key components are:

- **Input sequence**: \( x_1, x_2, \dots, x_T \)
- **Hidden states**: \( h_0, h_1, \dots, h_T \) (where \( h_0 \) is usually initialized to zeros)
- **Outputs**: \( y_1, y_2, \dots, y_T \)
- **Weight matrices**:
  - \( U \): Input-to-hidden weights
  - \( W \): Hidden-to-hidden weights (recurrent connections)
  - \( V \): Hidden-to-output weights
- **Bias vectors**:
  - \( b \): Hidden bias
  - \( c \): Output bias

## Mathematical Formulation

For each time step \( t \) from 1 to \( T \):

1. **Hidden state computation**:
   \[
   h_t = \tanh(U \cdot x_t + W \cdot h_{t-1} + b)
   \]

2. **Output computation** (for classification tasks):
   \[
   y_t = \softmax(V \cdot h_t + c)
   \]

   Or for regression tasks:
   \[
   y_t = V \cdot h_t + c
   \]

The activation function \(\tanh\) is commonly used for the hidden layer, and \(\softmax\) for multi-class classification outputs.

## Code Implementation

The above code implements the forward propagation for a basic RNN. Let's break it down:

1. **Initialization**: We initialize the hidden states array with zeros, and the first hidden state \( h_0 \) is set to zeros.

2. **Loop over time steps**: For each time step \( t \), we compute:
   - The hidden state \( h_t \) using the input \( x_t \), previous hidden state \( h_{t-1} \), and the weights U, W, and bias b.
   - The output \( y_t \) using the current hidden state \( h_t \), weights V, and bias c.

3. **Activation functions**: We use \(\tanh\) for hidden states and \(\softmax\) for outputs (assuming classification).

## Example Usage

## Understanding the Output

- **Input sequence shape**: (5, 3) - 5 time steps, each with 3-dimensional input
- **Hidden states shape**: (6, 4) - 6 hidden states (including initial h0), each 4-dimensional
- **Outputs shape**: (5, 2) - 5 outputs, each with 2 classes (probabilities sum to 1)

The hidden states capture the sequential information, and the outputs provide predictions for each time step.

## Key Points

1. **Sequential Processing**: RNNs process inputs one time step at a time, maintaining state across steps.
2. **Parameter Sharing**: The same weights U, W, V are used at every time step.
3. **Vanishing Gradient**: The repeated multiplication of W can cause gradients to vanish during backpropagation.
4. **Variants**: LSTM and GRU were developed to address the vanishing gradient problem.

This implementation demonstrates the core forward propagation mechanism of RNNs.

In [1]:
import numpy as np

def rnn_forward_propagation(X, U, W, V, b, c):
    """
    Perform forward propagation for a simple RNN.

    Parameters:
    X: Input sequence of shape (T, D) where T is sequence length, D is input dimension
    U: Input-to-hidden weights of shape (H, D)
    W: Hidden-to-hidden weights of shape (H, H)
    V: Hidden-to-output weights of shape (K, H)
    b: Hidden bias of shape (H,)
    c: Output bias of shape (K,)

    Returns:
    h: Hidden states for all time steps, shape (T+1, H) including h0
    y: Outputs for all time steps, shape (T, K)
    """
    T, D = X.shape
    H = U.shape[0]  # Hidden dimension
    K = V.shape[0]  # Output dimension

    # Initialize hidden states
    h = np.zeros((T+1, H))
    h[0] = np.zeros(H)  # h0 is zeros

    # Initialize outputs
    y = np.zeros((T, K))

    # Forward propagation
    for t in range(1, T+1):
        # Hidden state
        h[t] = np.tanh(np.dot(U, X[t-1]) + np.dot(W, h[t-1]) + b)

        # Output
        y[t-1] = softmax(np.dot(V, h[t]) + c)

    return h, y

def softmax(x):
    """Compute softmax values for each set of scores in x."""
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

In [2]:
# Example usage
np.random.seed(42)  # For reproducibility

# Define dimensions
T = 5  # Sequence length
D = 3  # Input dimension
H = 4  # Hidden dimension
K = 2  # Output dimension (e.g., binary classification)

# Generate random input sequence
X = np.random.randn(T, D)

# Initialize weights and biases randomly
U = np.random.randn(H, D)
W = np.random.randn(H, H)
V = np.random.randn(K, H)
b = np.random.randn(H)
c = np.random.randn(K)

# Perform forward propagation
h, y = rnn_forward_propagation(X, U, W, V, b, c)

print("Input sequence shape:", X.shape)
print("Hidden states shape:", h.shape)
print("Outputs shape:", y.shape)
print("\nHidden states:")
print(h)
print("\nOutputs (probabilities):")
print(y)

Input sequence shape: (5, 3)
Hidden states shape: (6, 4)
Outputs shape: (5, 2)

Hidden states:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.10235232e-01  1.66031570e-02 -4.07491712e-01 -2.25063301e-04]
 [-7.95197135e-01 -9.76515701e-01  9.43241236e-01  3.15631773e-01]
 [-9.82849892e-01 -9.99989542e-01 -4.81528954e-01  4.42339701e-02]
 [-2.19232200e-02 -9.85478740e-01  9.95028684e-01  1.98056988e-01]
 [ 7.81381682e-01 -9.27398316e-01  4.56886899e-01  9.69743587e-01]]

Outputs (probabilities):
[[0.85026701 0.14973299]
 [0.9953499  0.0046501 ]
 [0.98775734 0.01224266]
 [0.98877746 0.01122254]
 [0.8923235  0.1076765 ]]
